/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.MyLibrary;
import model.Persona;
import model.Sesso;

/**
 *
 * @author Tony
 */
public class NuovaPersona extends javax.swing.JFrame {

    /**
     * Creates new form NuovaPersona
     */
    private String path="dati.dat";
    public NuovaPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitle = new javax.swing.JLabel();
        lblnome = new javax.swing.JLabel();
        lblcognome = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblluogonascita = new javax.swing.JLabel();
        textnome = new javax.swing.JTextField();
        textcognome = new javax.swing.JTextField();
        textdata = new javax.swing.JTextField();
        textluogo = new javax.swing.JTextField();
        lblSesso = new javax.swing.JLabel();
        radioaltro = new javax.swing.JRadioButton();
        radiomaschio = new javax.swing.JRadioButton();
        radioFemmina = new javax.swing.JRadioButton();
        btnsalva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbltitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltitle.setText("Nuova Persona");

        lblnome.setText("Nome");

        lblcognome.setText("Cognome");

        lblData.setText("Data");

        lblluogonascita.setText("Luogo Di Nascita:");

        lblSesso.setText("Sesso :");

        radioaltro.setText("Altro");

        radiomaschio.setText("Maschio");

        radioFemmina.setText("Femmina");

        btnsalva.setText("Salva");
        btnsalva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalvaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(198, Short.MAX_VALUE)
                        .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblluogonascita)
                                .addGap(37, 37, 37)
                                .addComponent(textluogo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblnome)
                                .addGap(93, 93, 93)
                                .addComponent(textnome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblcognome)
                                .addGap(75, 75, 75)
                                .addComponent(textcognome))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblData)
                                .addGap(97, 97, 97)
                                .addComponent(textdata))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSesso)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radiomaschio)
                                    .addComponent(radioaltro)
                                    .addComponent(radioFemmina))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnsalva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblnome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcognome)
                    .addComponent(textcognome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(textdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblluogonascita, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textluogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSesso)
                    .addComponent(radioaltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiomaschio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFemmina)
                    .addComponent(btnsalva, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalvaActionPerformed
    
        try {
            Persona p =new Persona();
            GregorianCalendar a =new GregorianCalendar();
            p.setNome(textnome.getText());
            p.setCognome(textcognome.getText());
            p.setLuogoNascita(textluogo.getText());
            GregorianCalendar gregorianCalendar;
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("dd/MM/yyyy");
            Date date = simpleDateFormat.parse(textdata.getText());
            gregorianCalendar =(GregorianCalendar) GregorianCalendar.getInstance();
            gregorianCalendar.setTime(date);
            p.setDataNascita(gregorianCalendar);
            
            if(radioaltro.isSelected())
                p.setSesso(Sesso.ALTRO);
            else if(radioFemmina.isSelected())
                p.setSesso(Sesso.FEMMINA);
            else if(radiomaschio.isSelected())
                p.setSesso(Sesso.MASCHIO);
            
            ArrayList<Persona> al = new ArrayList<Persona>();
            al.add(p);
            File f= new File(path);
            if(f.exists()){
                MyLibrary.append(path, p);
                JOptionPane.showMessageDialog(null, "Dato Salvato");
            }
            else 
                try {
                if(f.createNewFile())
                {
                    MyLibrary.scrivi(path, al);
                    JOptionPane.showMessageDialog(null, "Dato Salvato");
                   
                    
                }
            } catch (IOException ex) {
                Logger.getLogger(NuovaPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ParseException ex) {
            Logger.getLogger(NuovaPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_btnsalvaActionPerformed
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NuovaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NuovaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NuovaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NuovaPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NuovaPersona().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsalva;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblSesso;
    private javax.swing.JLabel lblcognome;
    private javax.swing.JLabel lblluogonascita;
    private javax.swing.JLabel lblnome;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JRadioButton radioFemmina;
    private javax.swing.JRadioButton radioaltro;
    private javax.swing.JRadioButton radiomaschio;
    private javax.swing.JTextField textcognome;
    private javax.swing.JTextField textdata;
    private javax.swing.JTextField textluogo;
    private javax.swing.JTextField textnome;
    // End of variables declaration//GEN-END:variables
}
