/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaster;

import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Alimentazione;
import model.Auto;
import model.MyLibrary;

/**
 *
 * @author favat
 */
public class NewPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewPersona
     */
    private String path="Auto.dat";
    public NewPersona() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextMarca = new javax.swing.JTextField();
        lblmarca = new javax.swing.JLabel();
        lblmodello = new javax.swing.JLabel();
        TextModello = new javax.swing.JTextField();
        lblcolore = new javax.swing.JLabel();
        textcolore = new javax.swing.JTextField();
        lblcilindrata = new javax.swing.JLabel();
        TextCilindrata = new javax.swing.JTextField();
        radiobenz = new javax.swing.JRadioButton();
        radioMetano = new javax.swing.JRadioButton();
        radioElettrica = new javax.swing.JRadioButton();
        radiodisel = new javax.swing.JRadioButton();
        radiogpl = new javax.swing.JRadioButton();
        btnAggiungi = new javax.swing.JButton();
        lbltitle = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblmarca.setText("Marca:");

        lblmodello.setText("Modello:");

        lblcolore.setText("Colore:");

        lblcilindrata.setText("Cilindrata:");

        radiobenz.setText("Benzina");

        radioMetano.setText("Metano");

        radioElettrica.setText("Elettrica");

        radiodisel.setText("Diesel");

        radiogpl.setText("GPL");

        btnAggiungi.setText("Aggiungi");
        btnAggiungi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAggiungiActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("Vani", 3, 24)); // NOI18N
        lbltitle.setText("Nuova Auto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(radioMetano)
                        .addGap(46, 46, 46)
                        .addComponent(radioElettrica)
                        .addGap(113, 113, 113))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcilindrata)
                                    .addGap(33, 33, 33)
                                    .addComponent(TextCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblcolore)
                                    .addGap(33, 33, 33)
                                    .addComponent(textcolore, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblmarca)
                                        .addComponent(lblmodello))
                                    .addGap(33, 33, 33)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(TextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextModello, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(btnAggiungi, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radiobenz)
                                .addGap(48, 48, 48)
                                .addComponent(radiodisel)
                                .addGap(55, 55, 55)
                                .addComponent(radiogpl)))
                        .addGap(78, 78, 78))))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmarca)
                    .addComponent(TextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmodello)
                    .addComponent(TextModello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcolore)
                    .addComponent(textcolore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcilindrata)
                    .addComponent(TextCilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiobenz)
                    .addComponent(radiodisel)
                    .addComponent(radiogpl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioElettrica)
                    .addComponent(radioMetano))
                .addGap(18, 18, 18)
                .addComponent(btnAggiungi, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAggiungiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAggiungiActionPerformed
        
        Auto a =new Auto();
        a.setMarca(TextMarca.getText());
        a.setModello(TextModello.getText());
        a.setColore(textcolore.getText());
        int cilindrata = Integer.parseInt(TextCilindrata.getText());
        a.setCilindrata(cilindrata);
        if(radiobenz.isSelected())
            a.setAlimentazione(Alimentazione.BENZINA);
        else if(radiodisel.isSelected())
            a.setAlimentazione(Alimentazione.DIESEL);
        else if(radiogpl.isSelected())
            a.setAlimentazione(Alimentazione.GPL);
        else if(radioMetano.isSelected())
            a.setAlimentazione(Alimentazione.METANO);
        else if(radioElettrica.isSelected())
            a.setAlimentazione(Alimentazione.ELETTRICA);
        ArrayList<Auto> al = new ArrayList<Auto>();
        al.add(a);
        File f= new File(path);
        if(f.exists()){
            MyLibrary.append(path, a);
            JOptionPane.showMessageDialog(null, "Dato Salvato");
        }
        else
            try {
                if(f.createNewFile())
                {
                    MyLibrary.scrivi(path, al);
                    JOptionPane.showMessageDialog(null, "Dato Salvato");
                    
                    
                }
            } catch (IOException ex) {
                Logger.getLogger(NewPersona.class.getName()).log(Level.SEVERE, null, ex);
            }
        this.dispose();
       

    }//GEN-LAST:event_btnAggiungiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextCilindrata;
    private javax.swing.JTextField TextMarca;
    private javax.swing.JTextField TextModello;
    private javax.swing.JButton btnAggiungi;
    private javax.swing.JLabel lblcilindrata;
    private javax.swing.JLabel lblcolore;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lblmodello;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JRadioButton radioElettrica;
    private javax.swing.JRadioButton radioMetano;
    private javax.swing.JRadioButton radiobenz;
    private javax.swing.JRadioButton radiodisel;
    private javax.swing.JRadioButton radiogpl;
    private javax.swing.JTextField textcolore;
    // End of variables declaration//GEN-END:variables

    private void log(Level SEVERE, Object object, IOException ex) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
