/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaster;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import model.Alimentazione;
import model.Auto;
import model.MyLibrary;

/**
 *
 * @author favat
 */
public class Stampa extends javax.swing.JInternalFrame {
private String path="Auto.dat";
private String pathe="Auto.txt";
private int cerca;
private Auto a=null;
private ArrayList<Auto>al=null;
    /**
     * Creates new form Stampa
     */
    public Stampa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitleStampa = new javax.swing.JLabel();
        lblmarca = new javax.swing.JLabel();
        radiogpl = new javax.swing.JRadioButton();
        lblcognome = new javax.swing.JLabel();
        radiodiesel = new javax.swing.JRadioButton();
        lblcolore = new javax.swing.JLabel();
        textmarca = new javax.swing.JTextField();
        lblCilindrata = new javax.swing.JLabel();
        textcerca = new javax.swing.JTextField();
        textcilindrata = new javax.swing.JTextField();
        textColore = new javax.swing.JTextField();
        textmodello = new javax.swing.JTextField();
        lblelicerca = new javax.swing.JLabel();
        lblAlimentazione = new javax.swing.JLabel();
        btncerca = new javax.swing.JButton();
        btnStampa = new javax.swing.JButton();
        radiobenz = new javax.swing.JRadioButton();
        radiometano = new javax.swing.JRadioButton();
        radioElettrica = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lbltitleStampa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltitleStampa.setText("Stampa");

        lblmarca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblmarca.setText("Marca :");

        radiogpl.setText("GPL");

        lblcognome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcognome.setText("Modello:");

        radiodiesel.setText("Diesel");

        lblcolore.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblcolore.setText("Colore:");

        lblCilindrata.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblCilindrata.setText("Cilindrata:");

        lblelicerca.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblelicerca.setText("Cerca per id:");

        lblAlimentazione.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAlimentazione.setText("Alimentazione");

        btncerca.setText("Cerca");
        btncerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncercaActionPerformed(evt);
            }
        });

        btnStampa.setText("Stampa");
        btnStampa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStampaActionPerformed(evt);
            }
        });

        radiobenz.setText("Benzina");

        radiometano.setText("Metano");

        radioElettrica.setText("Elettrica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(256, 256, 256)
                .addComponent(lbltitleStampa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(264, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioElettrica)
                    .addComponent(radiometano))
                .addGap(239, 239, 239))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(91, 91, 91)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCilindrata)
                        .addComponent(lblelicerca)
                        .addComponent(lblmarca, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblcognome, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblcolore, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblAlimentazione, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(radiogpl)
                                .addComponent(radiobenz)
                                .addComponent(textmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(textmodello)
                                .addComponent(textColore)
                                .addComponent(textcilindrata))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(radiodiesel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStampa, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textcerca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                                .addComponent(btncerca, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(91, 91, 91)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitleStampa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addComponent(radiometano)
                .addGap(18, 18, 18)
                .addComponent(radioElettrica)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(83, 83, 83)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblelicerca)
                        .addComponent(textcerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btncerca, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblmarca)
                        .addComponent(textmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcognome)
                        .addComponent(textmodello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcolore)
                        .addComponent(textColore, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCilindrata)
                        .addComponent(textcilindrata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblAlimentazione)
                        .addComponent(radiobenz))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radiodiesel)
                        .addComponent(btnStampa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radiogpl)
                    .addGap(84, 84, 84)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncercaActionPerformed

        cerca=Integer.parseInt(textcerca.getText());
        a=new Auto();
        al=new ArrayList<Auto>();
        al=MyLibrary.leggi(path);
        for(Object o : al){
            if(o instanceof Auto)
            a=(Auto)o;
        }
        textmarca.setText(al.get(cerca).getMarca());
        textmodello.setText(al.get(cerca).getModello());
        textColore.setText(al.get(cerca).getColore());
        textcilindrata.setText(Integer.toString(al.get(cerca).getCilindrata()));
        if(al.get(cerca).getAlimentazione()==Alimentazione.BENZINA)
        radiobenz.doClick();
        if(al.get(cerca).getAlimentazione()==Alimentazione.DIESEL)
        radiodiesel.doClick();
        if(al.get(cerca).getAlimentazione()==Alimentazione.GPL)
        radiogpl.doClick();
        if(al.get(cerca).getAlimentazione()==Alimentazione.METANO)
        radiometano.doClick();
        if(al.get(cerca).getAlimentazione()==Alimentazione.ELETTRICA)
        radioElettrica.doClick();
        
        
        
        
    }//GEN-LAST:event_btncercaActionPerformed

    private void btnStampaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStampaActionPerformed
       
            al.get(cerca).setMarca(textmarca.getText());
            al.get(cerca).setModello(textmodello.getText());
            al.get(cerca).setColore(textColore.getText());
            String b =Integer.toString(al.get(cerca).getCilindrata());
            
         

            

            if(radiobenz.isSelected())
            al.get(cerca).setAlimentazione(Alimentazione.BENZINA);
            if(radiodiesel.isSelected())
            al.get(cerca).setAlimentazione(Alimentazione.DIESEL);
            if(radiogpl.isSelected())
            al.get(cerca).setAlimentazione(Alimentazione.GPL);
            if(radiometano.isSelected())
            al.get(cerca).setAlimentazione(Alimentazione.METANO);
            if(radioElettrica.isSelected())
            al.get(cerca).setAlimentazione(Alimentazione.ELETTRICA);
            if(a!=null){
            MyLibrary.scrivitxt(pathe, a);
            JOptionPane.showMessageDialog(null,"Auto Stampata");
            this.dispose();
           
            }
            else{
            JOptionPane.showMessageDialog(null,"Auto non esiste");
            }
            
            
            

        
    }//GEN-LAST:event_btnStampaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStampa;
    private javax.swing.JButton btncerca;
    private javax.swing.JLabel lblAlimentazione;
    private javax.swing.JLabel lblCilindrata;
    private javax.swing.JLabel lblcognome;
    private javax.swing.JLabel lblcolore;
    private javax.swing.JLabel lblelicerca;
    private javax.swing.JLabel lblmarca;
    private javax.swing.JLabel lbltitleStampa;
    private javax.swing.JRadioButton radioElettrica;
    private javax.swing.JRadioButton radiobenz;
    private javax.swing.JRadioButton radiodiesel;
    private javax.swing.JRadioButton radiogpl;
    private javax.swing.JRadioButton radiometano;
    private javax.swing.JTextField textColore;
    private javax.swing.JTextField textcerca;
    private javax.swing.JTextField textcilindrata;
    private javax.swing.JTextField textmarca;
    private javax.swing.JTextField textmodello;
    // End of variables declaration//GEN-END:variables
}
