/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guimaster;

import java.util.ArrayList;
import model.Auto;
import model.MyLibrary;

/**
 *
 * @author favat
 */
public class Visualizza extends javax.swing.JInternalFrame {

    /**
     * Creates new form Visualizza
     */
    private String path="Auto.dat";
    public Visualizza() {
        
        int i=0;   
        initComponents();
        ArrayList<Auto> al= new ArrayList<Auto>();
        al=MyLibrary.leggi(path);
        for(Object o :al){
           Auto p =null;
            if(o instanceof Auto){
                p=(Auto)o;
                textareavisualizza.append(p.toString()+"\n\n");
            i++;
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblVisualizza = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textareavisualizza = new javax.swing.JTextArea();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblVisualizza.setFont(new java.awt.Font("MV Boli", 0, 36)); // NOI18N
        lblVisualizza.setText("Visualizza");

        textareavisualizza.setColumns(20);
        textareavisualizza.setRows(5);
        jScrollPane1.setViewportView(textareavisualizza);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblVisualizza, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizza;
    private javax.swing.JTextArea textareavisualizza;
    // End of variables declaration//GEN-END:variables

    
}
